# Site settings
title: Algoritmia y Programación
email: profrgerhard+ap@gmail.com
description: Sitio Web Oficial del Proyecto de Algoritmia y Programación
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/AlgoritmiaTecnmI3
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/tecnm_development_club_iti3?igshid=YmMyMTA2M2Y=
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
